// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace ASP_Net_Forum_Service
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Id")]
            public float Id { get; set; }

            [ColumnName(@"NoteId")]
            public float NoteId { get; set; }

            [ColumnName(@"CategoryId")]
            public float CategoryId { get; set; }

            [ColumnName(@"ValueMark")]
            public float ValueMark { get; set; }

            [ColumnName(@"Mark")]
            public float Mark { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"Id")]
            public uint Id { get; set; }

            [ColumnName(@"NoteId")]
            public uint NoteId { get; set; }

            [ColumnName(@"CategoryId")]
            public float CategoryId { get; set; }

            [ColumnName(@"ValueMark")]
            public float ValueMark { get; set; }

            [ColumnName(@"Mark")]
            public float Mark { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = "C:\\Users\\Artem\\Desktop\\Programs\\ASP.Net\\ASP.Net_Forum\\Servises\\MLModel1.zip";

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
