version: "3.1"

services:
  app:
    depends_on:
       - mysql
    image: artem06/aspnetforum
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development  
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1111"
