
// This file was auto-generated by ML.NET Model Builder. 

using MLModel_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel.ModelInput sampleData = new MLModel.ModelInput()
{
    UserId = 1F,
    MovieId = 3F,
    Timestamp = 9.649812E+08F,
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Rating with predicted Rating from sample data...\n\n");


Console.WriteLine($"UserId: {1F}");
Console.WriteLine($"MovieId: {3F}");
Console.WriteLine($"Rating: {4F}");
Console.WriteLine($"Timestamp: {9.649812E+08F}");


Console.WriteLine($"\n\nPredicted Rating: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

